@enum Version begin

  HISTORICAL_SCHEDULE         = 165
  ADVANCED_ORDER_REJECT       = 166
  USER_INFO                   = 167
  CRYPTO_AGGREGATED_TRADES    = 168
  MANUAL_ORDER_TIME           = 169
  PEGBEST_PEGMID_OFFSETS      = 170
  WSH_EVENT_DATA_FILTERS      = 171
  IPO_PRICES                  = 172
  WSH_EVENT_DATA_FILTERS_DATE = 173
  INSTRUMENT_TIMEZONE         = 174
  HMDS_MARKET_DATA_IN_SHARES  = 175
  BOND_ISSUERID               = 176

end
