@enum Version begin

  NO_DEFAULT_OPEN_CLOSE    = 155
  PRICE_BASED_VOLATILITY   = 156
  REPLACE_FA_END           = 157
  DURATION                 = 158
  MARKET_DATA_IN_SHARES    = 159
  POST_TO_ATS              = 160
  WSHE_CALENDAR            = 161
  AUTO_CANCEL_PARENT       = 162
  FRACTIONAL_SIZE_SUPPORT  = 163

end
