@enum Version begin

  WHAT_IF_EXT_FIELDS       = 142
  SCANNER_GENERIC_OPTS     = 143
  API_BIND_ORDER           = 144
  ORDER_CONTAINER          = 145
  SMART_DEPTH              = 146
  REMOVE_NULL_ALL_CASTING  = 147
  D_PEG_ORDERS             = 148
  MKT_DEPTH_PRIM_EXCHANGE  = 149
  COMPLETED_ORDERS         = 150
  PRICE_MGMT_ALGO          = 151
  STOCK_TYPE               = 152
  ENCODE_MSG_ASCII7        = 153
  SEND_ALL_FAMILY_CODES    = 154
  NO_DEFAULT_OPEN_CLOSE    = 155
  PRICE_BASED_VOLATILITY   = 156
  REPLACE_FA_END           = 157

end
